app:
  name: foo
 
image:
  repo: hashicorp/http-echo
  tag: latest
  imagePullPolicy: "Always"
  replicas: 1
  containerPort: 8080
  resources:
    requests:
      cpu: "50m"
      memory: "50Mi"
    limits:
      cpu: "150m"
      memory: "200Mi"
service:
  type: ClusterIP
  port: 8000
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"

